package data

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"time"

	_ "github.com/mattn/go-sqlite3"
)

var db *sql.DB

// InitDB initializes the SQLite database
func InitDB(dbPath string) error {
	// Ensure the directory exists
	dir := filepath.Dir(dbPath)
	if err := os.MkdirAll(dir, os.ModePerm); err != nil {
		return fmt.Errorf("failed to create database directory: %w", err)
	}

	var err error
	db, err = sql.Open("sqlite3", dbPath)
	if err != nil {
		return fmt.Errorf("failed to open database: %w", err)
	}

	if err = db.Ping(); err != nil {
		return fmt.Errorf("failed to ping database: %w", err)
	}

	// Enable foreign keys
	db.Exec("PRAGMA foreign_keys = ON")

	// Create tables
	if err := createTables(); err != nil {
		return fmt.Errorf("failed to create tables: %w", err)
	}

	// Run migrations
	if err := migrateDatabase(); err != nil {
		return fmt.Errorf("failed to run database migrations: %w", err)
	}

	return nil
}

// CloseDB closes the database connection
func CloseDB() error {
	if db != nil {
		return db.Close()
	}
	return nil
}

// GetDB returns the database instance
func GetDB() *sql.DB {
	return db
}

func createTables() error {
	// Users table
	usersTable := `
	CREATE TABLE IF NOT EXISTS users (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		username TEXT UNIQUE NOT NULL,
		password_hash TEXT NOT NULL,
		role TEXT NOT NULL DEFAULT 'user',
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	);
	CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
	CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
	`

	if _, err := db.Exec(usersTable); err != nil {
		return fmt.Errorf("failed to create users table: %w", err)
	}

	// Repo configs table
	repoConfigsTable := `
	CREATE TABLE IF NOT EXISTS repo_configs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT UNIQUE NOT NULL,
		url TEXT NOT NULL,
		branch TEXT NOT NULL DEFAULT 'main',
		vcs_type TEXT NOT NULL DEFAULT 'git',
		display_name TEXT,
		enabled INTEGER NOT NULL DEFAULT 1,
		ms_between_polls INTEGER DEFAULT 30000,
		vcs_config TEXT,
		exclude_dot_files INTEGER DEFAULT 0,
		enable_poll_updates INTEGER DEFAULT 1,
		enable_push_updates INTEGER DEFAULT 0,
		auto_generated_files TEXT,
		user_id INTEGER NOT NULL DEFAULT 0,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	);
	CREATE INDEX IF NOT EXISTS idx_repo_configs_name ON repo_configs(name);
	CREATE INDEX IF NOT EXISTS idx_repo_configs_enabled ON repo_configs(enabled);
	CREATE INDEX IF NOT EXISTS idx_repo_configs_user_id ON repo_configs(user_id);
	`

	if _, err := db.Exec(repoConfigsTable); err != nil {
		return fmt.Errorf("failed to create repo_configs table: %w", err)
	}

	return nil
}

// migrateDatabase runs database migrations to upgrade the schema
func migrateDatabase() error {
	// Check if user_id column exists in repo_configs table
	var colExists int
	err := db.QueryRow(`
		SELECT COUNT(*) FROM pragma_table_info('repo_configs') WHERE name = 'user_id'
	`).Scan(&colExists)
	if err != nil {
		return fmt.Errorf("failed to check user_id column: %w", err)
	}

	// Add user_id column if it doesn't exist
	if colExists == 0 {
		_, err = db.Exec(`ALTER TABLE repo_configs ADD COLUMN user_id INTEGER NOT NULL DEFAULT 0`)
		if err != nil {
			return fmt.Errorf("failed to add user_id column: %w", err)
		}
	}

	// Create index if it doesn't exist
	_, err = db.Exec(`CREATE INDEX IF NOT EXISTS idx_repo_configs_user_id ON repo_configs(user_id)`)
	if err != nil {
		return fmt.Errorf("failed to create user_id index: %w", err)
	}

	return nil
}

// User represents a user in the system
type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"-"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// RepoConfig represents a repository configuration
type RepoConfig struct {
	ID                 int64     `json:"id"`
	Name               string    `json:"name"`
	URL                string    `json:"url"`
	Branch             string    `json:"branch"`
	VcsType            string    `json:"vcsType"`
	DisplayName        string    `json:"displayName"`
	Enabled            bool      `json:"enabled"`
	MsBetweenPolls     int       `json:"msBetweenPolls"`
	VcsConfig          string    `json:"vcsConfig"`
	ExcludeDotFiles    bool      `json:"excludeDotFiles"`
	EnablePollUpdates  bool      `json:"enablePollUpdates"`
	EnablePushUpdates  bool      `json:"enablePushUpdates"`
	AutoGeneratedFiles string    `json:"autoGeneratedFiles"`
	UserID             int64     `json:"userId"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}
