package data

import (
	"database/sql"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	_ "github.com/mattn/go-sqlite3"
)

var db *sql.DB

// InitDB initializes the SQLite database
func InitDB(dbPath string) error {
	// Ensure directory exists
	dir := filepath.Dir(dbPath)
	if err := os.MkdirAll(dir, os.ModePerm); err != nil {
		return fmt.Errorf("failed to create database directory: %w", err)
	}

	var err error
	db, err = sql.Open("sqlite3", dbPath)
	if err != nil {
		return fmt.Errorf("failed to open database: %w", err)
	}

	if err = db.Ping(); err != nil {
		return fmt.Errorf("failed to ping database: %w", err)
	}

	// Enable foreign keys
	db.Exec("PRAGMA foreign_keys = ON")

	return nil
}

// CloseDB closes the database connection
func CloseDB() error {
	if db != nil {
		return db.Close()
	}
	return nil
}

// GetDB returns the database instance
func GetDB() *sql.DB {
	return db
}

func createTables() error {
	// Users table
	usersTable := `
	CREATE TABLE IF NOT EXISTS users (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		username TEXT UNIQUE NOT NULL,
		password_hash TEXT NOT NULL,
		role TEXT NOT NULL DEFAULT 'user',
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	);
	CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
	CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
	`

	if _, err := db.Exec(usersTable); err != nil {
		return fmt.Errorf("failed to create users table: %w", err)
	}

	// Repo configs table
	repoConfigsTable := `
	CREATE TABLE IF NOT EXISTS repo_configs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT UNIQUE NOT NULL,
		url TEXT NOT NULL,
		branch TEXT NOT NULL DEFAULT 'main',
		vcs_type TEXT NOT NULL DEFAULT 'git',
		display_name TEXT,
		enabled INTEGER NOT NULL DEFAULT 1,
		ms_between_polls INTEGER DEFAULT 30000,
		vcs_config TEXT,
		exclude_dot_files INTEGER DEFAULT 0,
		enable_poll_updates INTEGER DEFAULT 1,
		enable_push_updates INTEGER DEFAULT 0,
		auto_generated_files TEXT,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	);
	CREATE INDEX IF NOT EXISTS idx_repo_configs_name ON repo_configs(name);
	CREATE INDEX IF NOT EXISTS idx_repo_configs_enabled ON repo_configs(enabled);
	`

	if _, err := db.Exec(repoConfigsTable); err != nil {
		return fmt.Errorf("failed to create repo_configs table: %w", err)
	}

	return nil
}

// RebuildDatabase drops and recreates all tables
func RebuildDatabase() error {
	// Drop existing tables
	if _, err := db.Exec("DROP TABLE IF EXISTS users"); err != nil {
		return fmt.Errorf("failed to drop users table: %w", err)
	}
	if _, err := db.Exec("DROP TABLE IF EXISTS repo_configs"); err != nil {
		return fmt.Errorf("failed to drop repo_configs table: %w", err)
	}

	// Recreate tables
	return createTables()
}

// User represents a user in the system
type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"-"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// RepoConfig represents a repository configuration
type RepoConfig struct {
	ID                 int64     `json:"id"`
	Name               string    `json:"name"`
	URL                string    `json:"url"`
	Branch             string    `json:"branch"`
	VcsType            string    `json:"vcsType"`
	DisplayName        string    `json:"displayName"`
	Enabled            bool      `json:"enabled"`
	MsBetweenPolls     int       `json:"msBetweenPolls"`
	VcsConfig          string    `json:"vcsConfig"`
	ExcludeDotFiles    bool      `json:"excludeDotFiles"`
	EnablePollUpdates  bool      `json:"enablePollUpdates"`
	EnablePushUpdates  bool      `json:"enablePushUpdates"`
	AutoGeneratedFiles string    `json:"autoGeneratedFiles"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

// CreateUser creates a new user in the database
func CreateUser(username, passwordHash, role string) (*User, error) {
	log.Printf("[DB] Creating user: %s with role: %s", username, role)
	log.Printf("[DB] Password hash to store (len: %d): %s...", len(passwordHash), passwordHash[:min(30, len(passwordHash))]+"...")
	result, err := db.Exec(
		"INSERT INTO users (username, password_hash, role) VALUES (?, ?, ?)",
		username, passwordHash, role)
	if err != nil {
		log.Printf("[DB] Failed to create user: %v", err)
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return nil, fmt.Errorf("failed to get last insert id: %w", err)
	}

	log.Printf("[DB] User created with ID: %d", id)
	return GetUserByID(id)
}

// GetUserByID retrieves a user by ID
func GetUserByID(id int64) (*User, error) {
	user := &User{}
	err := db.QueryRow(
		"SELECT id, username, password_hash, role, created_at, updated_at FROM users WHERE id = ?",
		id).Scan(
		&user.ID, &user.Username, &user.PasswordHash, &user.Role,
		&user.CreatedAt, &user.UpdatedAt,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("failed to get user by username: %w", err)
	}
	return user, nil
}

// GetUserByUsername retrieves a user by username
func GetUserByUsername(username string) (*User, error) {
	user := &User{}
	err := db.QueryRow(
		"SELECT id, username, password_hash, role, created_at, updated_at FROM users WHERE username = ?",
		username).Scan(
		&user.ID, &user.Username, &user.PasswordHash, &user.Role,
		&user.CreatedAt, &user.UpdatedAt,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("failed to get user by username: %w", err)
	}
	// Debug: log the password_hash length
	log.Printf("[DB] Retrieved user %s, password_hash length: %d, password_hash: %s...",
		username, len(user.PasswordHash), user.PasswordHash[:min(30, len(user.PasswordHash))]+"...")
	return user, nil
}

// GetAllUsers retrieves all users
func GetAllUsers() ([]*User, error) {
	rows, err := db.Query(`
		SELECT id, username, password_hash, role, created_at, updated_at FROM users ORDER BY id ASC
	`)
	if err != nil {
		return nil, fmt.Errorf("failed to get all users: %w", err)
	}
	defer rows.Close()

	var users []*User
	for rows.Next() {
		user := &User{}
		if err := rows.Scan(
			&user.ID, &user.Username, &user.PasswordHash, &user.Role,
			&user.CreatedAt, &user.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan user: %w", err)
		}
		users = append(users, user)
	}
	return users, nil
}

// UpdateUser updates a user's information
func UpdateUser(id int64, username, passwordHash, role string) (*User, error) {
	now := time.Now()
	_, err := db.Exec(
		"UPDATE users SET username = ?, password_hash = ?, role = ?, updated_at = ? WHERE id = ?",
		username, passwordHash, role, now, id,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}
	return GetUserByID(id)
}

// UpdateUserRole updates only a user's role
func UpdateUserRole(id int64, role string) error {
	_, err := db.Exec("UPDATE users SET role = ?, updated_at = ? WHERE id = ?",
		role, time.Now(), id)
	return err
}

// DeleteUser deletes a user by ID
func DeleteUser(id int64) error {
	result, err := db.Exec("DELETE FROM users WHERE id = ?", id)
	if err != nil {
		return nil, fmt.Errorf("failed to delete user: %w", err)
	}
	rows, _ := result.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("user not found")
	}
	return nil
}

// UserCount returns total number of users
func UserCount() (int, error) {
	var count int
	err := db.QueryRow("SELECT COUNT(*) FROM users").Scan(&count)
	return count, err
}
